#!/bin/bash
# cclint - run mach format checking on modified files in C-C
# (eslint for javascript, clang-format for c++)

# Without args, it checks all modified files (changed, but not checked in).
# Use `-r <REV>` to check the files which were altered by changeset <REV>
# instead.

#TODO: check for existing $MCDIR rather than hardcoding it here
MCDIR=~/tb/mozilla
CCDIR="${MCDIR}/comm"

set -e
pushd "$CCDIR" >/dev/null

usage() { echo "Usage: $0 [-r <REV>]" 1>&2; exit 1; }

rev=""
while getopts "r:" opt; do
    case "$opt" in
    r)  rev=${OPTARG}
        ;;
    *)  usage
        ;;
    esac
done
shift $((OPTIND-1))

if [ -z "$rev" ]; then
    rev="@"
fi

changed="$(jj diff -r $rev --name-only)"

for f in $changed
do
    echo "../mach commlint \"$f\" -W"
    ../mach commlint "$f" -W
done

popd >/dev/null
