#!/bin/bash
# cclint - run mach format checking on modified files in C-C
# (eslint for javascript, clang-format for c++)

# Without args, it checks all modified files (changed, but not checked in).
# Use `-r <REV>` to check the files which were altered by changeset <REV>
# instead.

#TODO: check for existing $MCDIR rather than hardcoding it here
MCDIR=~/tb/mozilla
CCDIR="${MCDIR}/comm"

set -e
pushd "$CCDIR" >/dev/null

usage() { echo "Usage: $0 [-r <REV>]" 1>&2; exit 1; }

rev=""
while getopts "r:" opt; do
    case "$opt" in
    r)  rev=${OPTARG}
        ;;
    *)  usage
        ;;
    esac
done
shift $((OPTIND-1))

if [ -z "$rev" ]; then
    # no revision - use locally-modified files.
    changed="$(hg status -m -a -n)"
else
    # get files modified by specific changeset
    changed="$(hg status -m -a -n --change $rev)"
fi


for f in $changed
do
    echo "../mach commlint \"$f\""
    ../mach commlint "$f"
done

popd >/dev/null
