@startuml
skinparam linetype ortho
left to right direction

interface nsIImapService
note bottom of nsIImapService
  Provides a friendlier front end for kicking off IMAP operations.
  Behind the scenes, it composes and issues "imap://" urls and sets up
  assorted state and listeners for handling the responses.
  Usually results in a stateful nsImapUrl object representing the request.
end note
interface nsIMsgMessageService
note bottom of nsIMsgMessageService
  UI-oriented operations on messages - display a message, copy messages,
  save to disk, download attachments etc...
end note
interface nsIMsgMessageFetchPartService
interface nsIProtocolHandler


note bottom of nsIProtocolHandler
  Handles creating channels for 'imap://...' urls.
end note

interface nsIMsgProtocolInfo
interface nsIContentHandler


class nsImapService
nsIImapService <|-- nsImapService
nsIMsgMessageService <|-- nsImapService
nsIMsgMessageFetchPartService <|-- nsImapService
nsIProtocolHandler <|-- nsImapService
nsIMsgProtocolInfo <|-- nsImapService
nsIContentHandler <|-- nsImapService

@enduml
